### ISSUE TITLE
#1 Example test procedure

### ISSUE THREAD

**Issue by peep1** [peep1/basictests#1]
This is an example of a test procedure.
This has been edited.
# tag1

**Comment by peep2** [comment]
#tag1  Band Blocks
#tag2 Frequency Blocks
......
Is that Correct?

**Comment by peep1** [comment]
I see you have the hang of it already!
To search for an entry, click this link:
https://github.com/peep1/basictests/search?utf8=%E2%9C%93&q=&type=Issues

**Comment by peep1** [comment]
Ref: https://github.com/peep1/basictests/blob/master/Test_00001.txt

**Comment by peep2** [comment]
this link cannot be opened

From: peep1
Date: 2015-05-20 08:12
To: peep1/basictests
CC: peep2
Subject: Re: [basictests] #1 Example test procedure (#1)
Ref: https://github.com/peep1/basictests/blob/master/Test_00001.txt

**Comment by peep2** [comment]
this file cannot be opened !
